import Link from "next/link";

import { requirePeopleContext } from "@/lib/people/context";

type SearchParams = Promise<{ search?: string; status?: string; page?: string }>;
function pageNumber(value?: string) { const number = Number(value ?? "1"); return Number.isInteger(number) && number > 0 ? number : 1; }

export default async function TeachersPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams; const { supabase, schoolId } = await requirePeopleContext("teachers", "view"); const search = params.search?.trim() ?? ""; const status = params.status ?? "active"; const page = pageNumber(params.page); const pageSize = 12;
  let query = supabase.from("teachers").select("id,employee_code,first_name,last_name,email,phone,specialization,employment_status").eq("school_id", schoolId).order("last_name").range((page - 1) * pageSize, page * pageSize);
  if (search) query = query.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%,employee_code.ilike.%${search}%`); if (status !== "all") query = query.eq("employment_status", status);
  const { data } = await query; const teachers = (data ?? []) as Array<Record<string, unknown>>;
  const next = (value: number) => `/teachers?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}&page=${value}`;
  return <main className="students-shell"><header className="students-header"><Link className="wordmark" href="/"><span className="wordmark-mark">S</span><span>schooliva</span></Link><div><Link className="text-action" href="/staff">Staff -&gt;</Link><Link className="text-action students-header-link" href="/dashboard">Dashboard -&gt;</Link></div></header><section className="students-heading"><div><p className="eyebrow">People / teachers</p><h1>Teachers.</h1><p>Manage faculty identity, employment status and academic assignments.</p></div><Link className="student-primary-action" href="/teachers/new">Add teacher <span>+</span></Link></section><form className="student-filters"><input name="search" defaultValue={search} placeholder="Search name or employee ID" /><select name="status" defaultValue={status}><option value="active">Active teachers</option><option value="inactive">Inactive teachers</option><option value="on_leave">On leave</option><option value="terminated">Terminated</option><option value="all">All statuses</option></select><button type="submit">Filter</button></form><div className="student-table-wrap"><table className="student-table"><thead><tr><th>Teacher</th><th>Employee ID</th><th>Contact</th><th>Specialization</th><th>Status</th></tr></thead><tbody>{teachers.length ? teachers.map((teacher) => <tr key={String(teacher.id)}><td><Link href={`/teachers/${String(teacher.id)}`} className="student-name"><strong>{String(teacher.first_name ?? "")} {String(teacher.last_name ?? "")}</strong><small>View profile and assignments</small></Link></td><td>{String(teacher.employee_code)}</td><td>{String(teacher.email ?? teacher.phone ?? "-")}</td><td>{String(teacher.specialization ?? "-")}</td><td><span className={`status-pill ${String(teacher.employment_status)}`}>{String(teacher.employment_status).replace("_", " ")}</span></td></tr>) : <tr><td colSpan={5}><div className="student-empty"><h3>No teachers found</h3><p>Try changing your search or add the first teacher.</p></div></td></tr>}</tbody></table></div><div className="student-pagination"><span>Page {page}</span><div>{page > 1 && <Link href={next(page - 1)}>Previous</Link>}{teachers.length > pageSize && <Link href={next(page + 1)}>Next</Link>}</div></div></main>;
}