"use client";

import { useActionState } from "react";
import { saveTimetableEntry } from "@/app/actions/timetable";
import { SubmitButton } from "@/components/auth/submit-button";
import type { TimetableFormState } from "@/lib/timetable/schemas";

type Option = { id: string; name: string };
function Feedback({ state }: { state: TimetableFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Select({ label, name, options, value }: { label: string; name: string; options: Option[]; value?: string }) { return <label className="student-field">{label}<select name={name} defaultValue={value ?? ""} required><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
export function TimetableForm({ sessions, classes, sections, subjects, teachers }: { sessions: Option[]; classes: Option[]; sections: Option[]; subjects: Option[]; teachers: Option[] }) { const [state, action] = useActionState(saveTimetableEntry, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Academic session" name="academicSessionId" options={sessions} /><Select label="Class" name="classId" options={classes} /><Select label="Section" name="sectionId" options={sections} /><Select label="Subject" name="subjectId" options={subjects} /><Select label="Teacher" name="teacherId" options={teachers} /><label className="student-field">Day<select name="dayOfWeek" defaultValue="1"><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option><option value="7">Sunday</option></select></label><label className="student-field">Start time<input name="startsAt" type="time" required /></label><label className="student-field">End time<input name="endsAt" type="time" required /></label><label className="student-field">Room<input name="room" placeholder="Room 101" /></label><label className="student-field">Status<select name="status" defaultValue="active"><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label></div><SubmitButton>Add timetable entry</SubmitButton></form>; }