import Link from "next/link";
import { notFound } from "next/navigation";

import { ArchiveStudentForm, DocumentForm, EnrollmentForm, StudentForm } from "@/components/students/student-forms";
import { requireStudentContext } from "@/lib/students/context";

function relation<T>(value: unknown): T | null { return Array.isArray(value) ? (value[0] ?? null) as T : (value as T | null); }

export default async function StudentProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { supabase, schoolId } = await requireStudentContext("view");
  const [{ data: student }, { data: parents }, { data: enrollments }, { data: classes }, { data: sections }, { data: sessions }, { data: documents }] = await Promise.all([
    supabase.from("students").select("*").eq("id", id).eq("school_id", schoolId).maybeSingle(),
    supabase.from("student_parents").select("relationship,is_primary,parents(first_name,last_name,phone,email)").eq("student_id", id).eq("school_id", schoolId),
    supabase.from("student_enrollments").select("id,roll_number,enrolled_on,status,withdrawn_at,classes(name),sections(name),academic_sessions(name),academic_terms(name)").eq("student_id", id).eq("school_id", schoolId).order("enrolled_on", { ascending: false }),
    supabase.from("classes").select("id,name").eq("school_id", schoolId).eq("status", "active").order("name"),
    supabase.from("sections").select("id,name").eq("school_id", schoolId).eq("status", "active").order("name"),
    supabase.from("academic_sessions").select("id,name").eq("school_id", schoolId).eq("status", "active").order("starts_on", { ascending: false }),
    supabase.from("student_documents").select("id,document_type,document_name,storage_path,created_at,metadata").eq("student_id", id).eq("school_id", schoolId).order("created_at", { ascending: false }),
  ]);
  if (!student) notFound();
  const record = student as unknown as Record<string, string | null>; const studentParents = (parents ?? []) as Array<Record<string, unknown>>; const history = (enrollments ?? []) as Array<Record<string, unknown>>; const documentRows = (documents ?? []) as Array<Record<string, unknown>>;
  return <main className="student-profile-shell"><header className="students-header"><Link className="wordmark" href="/"><span className="wordmark-mark">S</span><span>schooliva</span></Link><Link className="text-action" href="/students">All students -&gt;</Link></header><section className="student-profile-heading"><div><p className="eyebrow">Student profile</p><h1>{record.first_name} {record.last_name}</h1><p>{record.admission_number} {record.student_identifier ? ` / ${record.student_identifier}` : ""}</p></div><span className={`status-pill ${record.status}`}>{record.status}</span></section><div className="student-profile-grid"><section className="student-panel"><div className="student-panel-heading"><h2>Identity and contact</h2><span>Permanent record</span></div><StudentForm student={record} /></section><aside className="student-profile-aside"><section className="student-panel"><div className="student-panel-heading"><h2>Parents & guardians</h2></div>{studentParents.length ? <ul className="relationship-list">{studentParents.map((item, index) => { const parent = relation<{ first_name: string; last_name: string; phone?: string; email?: string }>(item.parents); return <li key={index}><strong>{parent?.first_name} {parent?.last_name}</strong><span>{String(item.relationship ?? "guardian")}</span><small>{parent?.phone ?? parent?.email ?? "No contact"}</small></li>; })}</ul> : <p className="student-muted">No parent relationships recorded.</p>}</section><section className="student-panel"><div className="student-panel-heading"><h2>Enrollment history</h2><span>Never overwritten</span></div>{history.length ? <ul className="enrollment-list">{history.map((item) => <li key={String(item.id)}><strong>{relation<{ name: string }>(item.classes)?.name ?? "-"} / {relation<{ name: string }>(item.sections)?.name ?? "-"}</strong><span>{relation<{ name: string }>(item.academic_sessions)?.name ?? "-"} · roll {String(item.roll_number ?? "-")}</span><small>{String(item.enrolled_on)} · {String(item.status)}</small></li>)}</ul> : <p className="student-muted">No enrollment history yet.</p>}<EnrollmentForm studentId={id} sessions={sessions ?? []} classes={classes ?? []} sections={sections ?? []} /></section><section className="student-panel"><div className="student-panel-heading"><h2>Documents metadata</h2><span>Storage-ready</span></div>{documentRows.length ? <ul className="relationship-list">{documentRows.map((item) => <li key={String(item.id)}><strong>{String(item.document_name)}</strong><span>{String(item.document_type)}</span><small>{String(item.created_at).slice(0, 10)}</small></li>)}</ul> : <p className="student-muted">No document metadata recorded.</p>}<DocumentForm studentId={id} /></section><section className="student-panel student-danger-panel"><h2>Student lifecycle</h2><p>Archive a student without deleting their historical identity or enrollment records.</p><ArchiveStudentForm id={id} /></section></aside></div></main>;
}