"use client";

import { useActionState } from "react";
import { recordInventoryTransaction, saveInventoryCategory, saveInventoryItem, saveInventoryUnit, saveSupplier } from "@/app/actions/inventory";
import { SubmitButton } from "@/components/auth/submit-button";
import type { InventoryFormState } from "@/lib/inventory/schemas";

type Option = { id: string; name: string };

function Feedback({ state }: { state: InventoryFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Select({ label, name, options, required = true }: { label: string; name: string; options: Option[]; required?: boolean }) { return <label className="student-field">{label}<select name={name} required={required}><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }

export function CategoryForm() { const [state, action] = useActionState(saveInventoryCategory, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Category name<input name="name" required /></label></div><SubmitButton>Add category</SubmitButton></form>; }
export function UnitForm() { const [state, action] = useActionState(saveInventoryUnit, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Unit name<input name="name" required /></label><label className="student-field">Short name<input name="shortName" required /></label></div><SubmitButton>Add unit</SubmitButton></form>; }
export function SupplierForm() { const [state, action] = useActionState(saveSupplier, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Supplier name<input name="name" required /></label><label className="student-field">Contact person<input name="contactName" /></label><label className="student-field">Phone<input name="phone" /></label><label className="student-field">Email<input name="email" type="email" /></label><label className="student-field student-field-wide">Address<textarea name="address" rows={3} /></label></div><SubmitButton>Add supplier</SubmitButton></form>; }
export function ItemForm({ categories, units, suppliers }: { categories: Option[]; units: Option[]; suppliers: Option[] }) { const [state, action] = useActionState(saveInventoryItem, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Category" name="categoryId" options={categories} /><Select label="Unit" name="unitId" options={units} /><Select label="Supplier" name="supplierId" options={suppliers} /><label className="student-field">SKU<input name="sku" required /></label><label className="student-field">Item name<input name="name" required /></label><label className="student-field">Cost<input name="cost" type="number" min="0" step="0.01" required /></label><label className="student-field">Location<input name="location" /></label><label className="student-field">Minimum stock level<input name="minStockLevel" type="number" min="0" required /></label><label className="student-field">Current quantity<input name="currentQuantity" type="number" min="0" required /></label><label className="student-field">Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="student-field student-field-wide">Description<textarea name="description" rows={3} /></label></div><SubmitButton>Add item</SubmitButton></form>; }
export function StockTransactionForm({ items }: { items: Option[] }) { const [state, action] = useActionState(recordInventoryTransaction, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Item" name="itemId" options={items} /><label className="student-field">Transaction type<select name="transactionType" required><option value="stock_in">Stock in</option><option value="stock_out">Stock out</option><option value="adjustment">Adjustment</option><option value="return">Return</option></select></label><label className="student-field">Quantity<input name="quantity" type="number" step="1" required /></label><label className="student-field">Unit cost<input name="unitCost" type="number" min="0" step="0.01" /></label><label className="student-field">Reference<input name="reference" /></label><label className="student-field student-field-wide">Notes<textarea name="notes" rows={3} /></label></div><SubmitButton>Save stock movement</SubmitButton></form>; }
