"use client";

import { useActionState } from "react";
import { createLeaveRequest, decideLeave, saveLeaveType } from "@/app/actions/leave";
import { SubmitButton } from "@/components/auth/submit-button";
import type { LeaveFormState } from "@/lib/leave/schemas";

type Option = { id: string; name: string };
function Feedback({ state }: { state: LeaveFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Select({ label, name, options }: { label: string; name: string; options: Option[] }) { return <label className="student-field">{label}<select name={name} required><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
export function LeaveTypeForm() { const [state, action] = useActionState(saveLeaveType, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Leave type<input name="name" required /></label><label className="student-field student-field-wide">Description<textarea name="description" rows={3} /></label></div><SubmitButton>Add leave type</SubmitButton></form>; }
export function LeaveRequestForm({ types, students, teachers, staff }: { types: Option[]; students: Option[]; teachers: Option[]; staff: Option[] }) { const [state, action] = useActionState(createLeaveRequest, undefined); const subjects = [...students.map((item) => ({ ...item, name: `Student · ${item.name}` })), ...teachers.map((item) => ({ ...item, name: `Teacher · ${item.name}` })), ...staff.map((item) => ({ ...item, name: `Staff · ${item.name}` }))]; return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Leave type" name="leaveTypeId" options={types} /><label className="student-field">Subject type<select name="subjectType"><option value="student">Student</option><option value="teacher">Teacher</option><option value="staff">Staff</option></select></label><label className="student-field">Subject ID<input name="subjectId" list="leave-subject-options" placeholder="Search person..." required /><datalist id="leave-subject-options">{subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist></label><label className="student-field">Start date<input name="startDate" type="date" required /></label><label className="student-field">End date<input name="endDate" type="date" required /></label><label className="student-field student-field-wide">Reason<textarea name="reason" rows={4} required /></label><label className="student-field">Attachment path<input name="attachmentPath" placeholder="Storage path after upload" /></label></div><p className="student-form-note">Attachments use the protected Supabase Storage leave-attachments bucket.</p><SubmitButton>Submit leave request</SubmitButton></form>; }
export function LeaveDecisionForm({ id }: { id: string }) { const [state, action] = useActionState(decideLeave, undefined); return <form action={action} className="student-form"><Feedback state={state} /><input type="hidden" name="leaveRequestId" value={id} /><label className="student-field">Decision<select name="status"><option value="approved">Approve</option><option value="rejected">Reject</option><option value="completed">Complete</option></select></label><label className="student-field">Approver note<textarea name="approverNote" rows={2} /></label><SubmitButton>Save decision</SubmitButton></form>; }
