"use client";
import { useActionState, useState } from "react";
import { addGradeBoundary, changeExamStatus, createExam, removeExamSchedule, removeExamSubject, saveExamSchedule, saveExamSubject, saveExamType, saveGradingScale, submitMarks } from "@/app/actions/exams";
import { SubmitButton } from "@/components/auth/submit-button";
import type { ExamFormState } from "@/lib/exams/schemas";
type Option = { id: string; name: string };
function Feedback({ state }: { state: ExamFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Select({ label, name, options }: { label: string; name: string; options: Option[] }) { return <label className="student-field">{label}<select name={name} required><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
function TextField({ label, name, type = "text", placeholder, required = true }: { label: string; name: string; type?: string; placeholder?: string; required?: boolean }) { return <label className="student-field">{label}<input name={name} type={type} placeholder={placeholder} required={required} /></label>; }

export function ExamSubjectForm({ examId, classes, subjects }: { examId: string; classes: Option[]; subjects: Option[] }) { const [state, action] = useActionState(saveExamSubject, undefined); return <form action={action} className="student-form"><Feedback state={state} /><input type="hidden" name="examId" value={examId} /><div className="student-form-grid"><Select label="Class" name="classId" options={classes} /><Select label="Subject" name="subjectId" options={subjects} /><TextField label="Maximum marks" name="maximumMarks" type="number" /><TextField label="Passing marks (optional)" name="passingMarks" type="number" required={false} /></div><SubmitButton>Add subject</SubmitButton></form>; }

export function RemoveExamSubject({ id, examId }: { id: string; examId: string }) { const [state, action] = useActionState(removeExamSubject, undefined); return <form action={action} className="delete-form"><input type="hidden" name="id" value={id} /><input type="hidden" name="examId" value={examId} /><button type="submit">Remove</button>{state?.error && <span className="student-error">{state.error}</span>}</form>; }

export function ExamScheduleForm({ examId, examSubjects, sections }: { examId: string; examSubjects: Option[]; sections: Option[] }) { const [state, action] = useActionState(saveExamSchedule, undefined); return <form action={action} className="student-form"><Feedback state={state} /><input type="hidden" name="examId" value={examId} /><div className="student-form-grid"><Select label="Exam subject" name="examSubjectId" options={examSubjects} /><Select label="Section" name="sectionId" options={sections} /><TextField label="Scheduled on" name="scheduledOn" type="date" /><TextField label="Starts at" name="startsAt" type="time" /><TextField label="Ends at" name="endsAt" type="time" /><TextField label="Room (optional)" name="room" required={false} /></div><SubmitButton>Add schedule</SubmitButton></form>; }

export function RemoveExamSchedule({ id, examId }: { id: string; examId: string }) { const [state, action] = useActionState(removeExamSchedule, undefined); return <form action={action} className="delete-form"><input type="hidden" name="id" value={id} /><input type="hidden" name="examId" value={examId} /><button type="submit">Remove</button>{state?.error && <span className="student-error">{state.error}</span>}</form>; }

type MarkStudent = { id: string; name: string; admissionNumber: string; maximumMarks: number; existing?: { obtainedMarks?: number | null; grade?: string | null; remarks?: string | null } };

export function MarksEntryForm({ examId, examSubjectId, students, published }: { examId: string; examSubjectId: string; students: MarkStudent[]; published: boolean }) {
  const [state, action] = useActionState(submitMarks, undefined);
  const [records, setRecords] = useState(students.map((student) => ({ studentId: student.id, obtainedMarks: String(student.existing?.obtainedMarks ?? ""), grade: student.existing?.grade ?? "", remarks: student.existing?.remarks ?? "" })));
  const update = (studentId: string, field: "obtainedMarks" | "grade" | "remarks", value: string) => setRecords((current) => current.map((record) => record.studentId === studentId ? { ...record, [field]: value } : record));
  const payload = records.map((record) => ({ studentId: record.studentId, obtainedMarks: record.obtainedMarks === "" ? 0 : Number(record.obtainedMarks), grade: record.grade, remarks: record.remarks }));
  return <form action={action} className="attendance-marker"><input type="hidden" name="examId" value={examId} /><input type="hidden" name="examSubjectId" value={examSubjectId} /><input type="hidden" name="records" value={JSON.stringify(payload)} />{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}<div className="attendance-toolbar"><span>{students.length} enrolled students</span>{published && <span>Published - protected</span>}</div><div className="attendance-table-wrap"><table className="student-table"><thead><tr><th>Student</th><th>Admission</th><th>Obtained</th><th>Max</th><th>Grade</th><th>Remarks</th></tr></thead><tbody>{students.map((student) => { const record = records.find((item) => item.studentId === student.id) ?? { studentId: student.id, obtainedMarks: "", grade: "", remarks: "" }; return <tr key={student.id}><td><strong>{student.name}</strong></td><td>{student.admissionNumber}</td><td><input type="number" min="0" max={student.maximumMarks} step="0.01" disabled={published} value={record.obtainedMarks} onChange={(event) => update(student.id, "obtainedMarks", event.target.value)} /></td><td>{student.maximumMarks}</td><td><input disabled={published} value={record.grade} onChange={(event) => update(student.id, "grade", event.target.value)} /></td><td><input disabled={published} value={record.remarks} onChange={(event) => update(student.id, "remarks", event.target.value)} /></td></tr>; })}</tbody></table></div>{!published && <SubmitButton>Save marks</SubmitButton>}</form>;
}

export function ExamForm({ types, sessions, scales }: { types: Option[]; sessions: Option[]; scales: Option[] }) { const [state, action] = useActionState(createExam, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Exam type" name="examTypeId" options={types} /><Select label="Academic session" name="academicSessionId" options={sessions} /><Select label="Grading scale" name="gradingScaleId" options={scales} /><TextField label="Exam name" name="name" /><TextField label="Starts" name="startsOn" type="date" /><TextField label="Ends" name="endsOn" type="date" /></div><SubmitButton>Create exam</SubmitButton></form>; }

export function ExamStatusForm({ id, status }: { id: string; status: string }) { const [state, action] = useActionState(changeExamStatus, undefined); const next = status === "draft" ? "submitted" : status === "submitted" ? "reviewed" : "published"; return <form action={action}><input type="hidden" name="id" value={id} /><button className="table-edit" disabled={status === "published"} type="submit">{status === "published" ? "Published" : `Move to ${next}`}</button>{state?.error && <span className="student-error">{state.error}</span>}</form>; }

export function ExamTypeForm() { const [state, action] = useActionState(saveExamType, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><TextField label="Exam type name" name="name" placeholder="Monthly Test" /><TextField label="Description (optional)" name="description" required={false} /></div><SubmitButton>Add exam type</SubmitButton></form>; }

export function GradingScaleForm() { const [state, action] = useActionState(saveGradingScale, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><TextField label="Scale name" name="name" placeholder="Standard (A-F)" /><TextField label="Description (optional)" name="description" required={false} /></div><SubmitButton>Add grading scale</SubmitButton></form>; }

export function GradeBoundaryForm({ gradingScaleId }: { gradingScaleId: string }) { const [state, action] = useActionState(addGradeBoundary, undefined); return <form action={action} className="student-form"><Feedback state={state} /><input type="hidden" name="gradingScaleId" value={gradingScaleId} /><div className="student-form-grid"><TextField label="Grade" name="grade" placeholder="A" /><TextField label="Min %" name="minPercentage" type="number" /><TextField label="Max %" name="maxPercentage" type="number" /><TextField label="Grade point (optional)" name="gradePoint" type="number" required={false} /><TextField label="Remark (optional)" name="remark" required={false} /></div><SubmitButton>Add grade boundary</SubmitButton></form>; }