import Link from "next/link";
import Image from "next/image";

import { BootstrapSchoolForm, AssignmentForm, ClassForm, DeleteRecordForm, SchoolProfileForm, SectionForm, SessionForm, SettingsForm, SubjectForm, TermForm } from "@/components/setup/setup-forms";
import { requireUser } from "@/lib/auth/authorization";
import { requireSetupContext } from "@/lib/setup/context";

type SearchParams = Promise<{ section?: string; search?: string; page?: string; edit?: string; onboarding?: string }>;
const sections = [
  ["school", "School profile"], ["sessions", "Academic sessions"], ["terms", "Terms"], ["classes", "Classes"], ["sections", "Sections"], ["subjects", "Subjects"], ["assignments", "Class subjects"],
] as const;
type SetupRow = { id: string; name?: string; code?: string; starts_on?: string; ends_on?: string; status?: string; academic_sessions?: unknown; description?: string | null; capacity?: number | null; classes?: unknown; teachers?: unknown; subject_type?: string; subjects?: unknown; [key: string]: unknown };

function asPage(value?: string) { const parsed = Number(value ?? "1"); return Number.isInteger(parsed) && parsed > 0 ? parsed : 1; }
function asSearch(value?: string) { return value?.trim() ?? ""; }
function setupHref(section: string, search = "", page = 1) { const params = new URLSearchParams({ section }); if (search) params.set("search", search); if (page > 1) params.set("page", String(page)); return `/setup?${params.toString()}`; }
function relation<T>(value: unknown): T | null { return Array.isArray(value) ? (value[0] ?? null) as T : (value as T | null); }

function EmptyState({ label }: { label: string }) { return <div className="setup-empty"><span className="setup-empty-icon">+</span><h3>No {label} yet</h3><p>Start by adding your first {label.slice(0, -1)}.</p></div>; }

function Pagination({ section, search, page, hasNext }: { section: string; search: string; page: number; hasNext: boolean }) {
  return <div className="setup-pagination"><span>Page {page}</span><div>{page > 1 && <Link href={setupHref(section, search, page - 1)}>Previous</Link>}{hasNext && <Link href={setupHref(section, search, page + 1)}>Next</Link>}</div></div>;
}

export default async function SetupPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const current = await requireUser();
  const { data: membership } = await current.supabase.from("user_roles").select("school_id").eq("user_id", current.user.id).limit(1).maybeSingle();

  if (!membership?.school_id) return <main className="setup-onboarding"><div className="setup-onboarding-inner"><Link href="/" aria-label="Schooliva home"><Image className="setup-logo" src="/brand/logo.png" alt="Schooliva" width={240} height={240} priority /></Link><p className="eyebrow">School setup</p><h1>Set up your school.</h1><p className="setup-lede">Create the school workspace that will hold your academic structure and future operations.</p><BootstrapSchoolForm /></div></main>;

  const { supabase, schoolId } = await requireSetupContext();
  const section = sections.some(([key]) => key === params.section) ? params.section! : "school";
  const search = asSearch(params.search); const page = asPage(params.page); const pageSize = 8; const from = (page - 1) * pageSize; const to = from + pageSize;
  const [{ data: schoolData }, { data: settingsData }, { data: sessionsData }, { data: termsData }, { data: classesData }, { data: sectionsData }, { data: subjectsData }, { data: assignmentsData }, { data: teachersData }] = await Promise.all([
    supabase.from("schools").select("id,name,short_name,slug,code,school_type,campus,board,medium,email,phone,website,address,city,state,country,principal,established_year").eq("id", schoolId).maybeSingle(),
    supabase.from("school_settings").select("timezone,currency_code,date_format").eq("school_id", schoolId).maybeSingle(),
    supabase.from("academic_sessions").select("id,name,code,starts_on,ends_on,status").eq("school_id", schoolId).order("starts_on", { ascending: false }).ilike(search ? "name" : "code", search ? `%${search}%` : "%").range(from, to),
    supabase.from("academic_terms").select("id,name,code,starts_on,ends_on,status,academic_session_id,academic_sessions(name)").eq("school_id", schoolId).order("starts_on", { ascending: false }).ilike(search ? "name" : "code", search ? `%${search}%` : "%").range(from, to),
    supabase.from("classes").select("id,name,code,description,status").eq("school_id", schoolId).order("name").ilike(search ? "name" : "code", search ? `%${search}%` : "%").range(from, to),
    supabase.from("sections").select("id,name,code,capacity,status,class_id,classes(name),class_teacher_id,teachers(first_name,last_name)").eq("school_id", schoolId).order("name").ilike(search ? "name" : "code", search ? `%${search}%` : "%").range(from, to),
    supabase.from("subjects").select("id,name,code,subject_type,status").eq("school_id", schoolId).order("name").ilike(search ? "name" : "code", search ? `%${search}%` : "%").range(from, to),
    supabase.from("class_subjects").select("id,class_id,subject_id,classes(name),subjects(name,code)").eq("school_id", schoolId).range(from, to),
    supabase.from("teachers").select("id,first_name,last_name").eq("school_id", schoolId).eq("is_active", true).order("last_name"),
  ]);
  const sessions = (sessionsData ?? []) as unknown as SetupRow[]; const terms = (termsData ?? []) as unknown as SetupRow[]; const classes = (classesData ?? []) as unknown as SetupRow[]; const setupSections = (sectionsData ?? []) as unknown as SetupRow[]; const subjects = (subjectsData ?? []) as unknown as SetupRow[]; const assignments = (assignmentsData ?? []) as unknown as SetupRow[]; const teachers = (teachersData ?? []) as unknown as SetupRow[]; const school = (schoolData ?? {}) as Record<string, string | null>; const settings = (settingsData ?? {}) as Record<string, string | null>;
  const editRecord = params.edit ? ([...sessions, ...terms, ...classes, ...setupSections, ...subjects].find((item) => item.id === params.edit) as unknown as Record<string, string> | undefined) : undefined;

  return <main className="setup-shell"><header className="setup-header"><Link className="wordmark" href="/"><span className="wordmark-mark">S</span><span>schooliva</span></Link><div className="setup-header-actions"><span className="setup-header-label">School setup</span><Link className="text-action" href="/dashboard">Dashboard -&gt;</Link></div></header>
    <div className="setup-layout"><aside className="setup-sidebar"><p className="eyebrow">Configuration</p><h1>Build your school.</h1><nav aria-label="School setup sections">{sections.map(([key, label]) => <Link className={section === key ? "setup-nav-link active" : "setup-nav-link"} href={setupHref(key)} key={key}><span>{String(sections.findIndex(([item]) => item === key) + 1).padStart(2, "0")}</span>{label}</Link>)}</nav></aside>
      <section className="setup-content"><div className="setup-content-heading"><div><p className="eyebrow">{sections.find(([key]) => key === section)?.[1]}</p><h2>{section === "school" ? school.name ?? "School profile" : sections.find(([key]) => key === section)?.[1]}</h2></div>{section !== "school" && <form className="setup-search"><input name="search" defaultValue={search} placeholder="Search setup records..." /><input type="hidden" name="section" value={section} /><button type="submit">Search</button></form>}</div>
        {section === "school" && <><div className="setup-card"><SchoolProfileForm school={school} /></div><div className="setup-card"><h3>Academic configuration</h3><SettingsForm settings={settings} /></div></>}
        {section === "sessions" && <><div className="setup-card"><h3>{editRecord ? "Edit academic session" : "Add academic session"}</h3><SessionForm initial={editRecord} /></div><div className="setup-table-wrap"><table className="setup-table"><thead><tr><th>Name</th><th>Dates</th><th>Status</th><th /></tr></thead><tbody>{sessions.length ? sessions.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{item.starts_on} - {item.ends_on}</td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td><Link className="table-edit" href={`${setupHref(section, search, page)}&edit=${item.id}`}>Edit</Link><DeleteRecordForm table="academic_sessions" id={item.id} /></td></tr>) : <tr><td colSpan={4}><EmptyState label="sessions" /></td></tr>}</tbody></table><Pagination section={section} search={search} page={page} hasNext={sessions.length > pageSize} /></div></>}
        {section === "terms" && <><div className="setup-card"><h3>{editRecord ? "Edit academic term" : "Add academic term"}</h3><TermForm sessions={sessions as Array<{ id: string; name: string }>} initial={editRecord} /></div><div className="setup-table-wrap"><table className="setup-table"><thead><tr><th>Name</th><th>Session</th><th>Dates</th><th>Status</th><th /></tr></thead><tbody>{terms.length ? terms.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{relation<{ name: string }>(item.academic_sessions)?.name ?? "-"}</td><td>{item.starts_on} - {item.ends_on}</td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td><Link className="table-edit" href={`${setupHref(section, search, page)}&edit=${item.id}`}>Edit</Link><DeleteRecordForm table="academic_terms" id={item.id} /></td></tr>) : <tr><td colSpan={5}><EmptyState label="terms" /></td></tr>}</tbody></table><Pagination section={section} search={search} page={page} hasNext={terms.length > pageSize} /></div></>}
        {section === "classes" && <><div className="setup-card"><h3>{editRecord ? "Edit class" : "Add class"}</h3><ClassForm initial={editRecord} /></div><div className="setup-table-wrap"><table className="setup-table"><thead><tr><th>Class</th><th>Description</th><th>Status</th><th /></tr></thead><tbody>{classes.length ? classes.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{item.description || "-"}</td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td><Link className="table-edit" href={`${setupHref(section, search, page)}&edit=${item.id}`}>Edit</Link><DeleteRecordForm table="classes" id={item.id} /></td></tr>) : <tr><td colSpan={4}><EmptyState label="classes" /></td></tr>}</tbody></table><Pagination section={section} search={search} page={page} hasNext={classes.length > pageSize} /></div></>}
        {section === "sections" && <><div className="setup-card"><h3>{editRecord ? "Edit section" : "Add section"}</h3><SectionForm classes={classes as Array<{ id: string; name: string }>} teachers={teachers as Array<{ id: string; first_name: string; last_name: string }>} initial={editRecord} /></div><div className="setup-table-wrap"><table className="setup-table"><thead><tr><th>Section</th><th>Class</th><th>Teacher</th><th>Capacity</th><th>Status</th><th /></tr></thead><tbody>{setupSections.length ? setupSections.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{relation<{ name: string }>(item.classes)?.name ?? "-"}</td><td>{relation<{ first_name: string; last_name: string }>(item.teachers)?.first_name ?? "-"} {relation<{ first_name: string; last_name: string }>(item.teachers)?.last_name ?? ""}</td><td>{item.capacity || "-"}</td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td><Link className="table-edit" href={`${setupHref(section, search, page)}&edit=${item.id}`}>Edit</Link><DeleteRecordForm table="sections" id={item.id} /></td></tr>) : <tr><td colSpan={6}><EmptyState label="sections" /></td></tr>}</tbody></table><Pagination section={section} search={search} page={page} hasNext={setupSections.length > pageSize} /></div></>}
        {section === "subjects" && <><div className="setup-card"><h3>{editRecord ? "Edit subject" : "Add subject"}</h3><SubjectForm initial={editRecord} /></div><div className="setup-table-wrap"><table className="setup-table"><thead><tr><th>Subject</th><th>Type</th><th>Status</th><th /></tr></thead><tbody>{subjects.length ? subjects.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{(item.subject_type ?? "").replace("_", " ")}</td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td><Link className="table-edit" href={`${setupHref(section, search, page)}&edit=${item.id}`}>Edit</Link><DeleteRecordForm table="subjects" id={item.id} /></td></tr>) : <tr><td colSpan={4}><EmptyState label="subjects" /></td></tr>}</tbody></table><Pagination section={section} search={search} page={page} hasNext={subjects.length > pageSize} /></div></>}
        {section === "assignments" && <><div className="setup-card"><h3>Assign subject to class</h3><AssignmentForm classes={classes as Array<{ id: string; name: string }>} subjects={subjects as Array<{ id: string; name: string }>} /></div><div className="setup-table-wrap"><table className="setup-table"><thead><tr><th>Class</th><th>Subject</th><th /></tr></thead><tbody>{assignments.length ? assignments.map((item) => <tr key={item.id}><td>{relation<{ name: string }>(item.classes)?.name ?? "-"}</td><td>{relation<{ name: string; code: string }>(item.subjects)?.name ?? "-"}<small>{relation<{ name: string; code: string }>(item.subjects)?.code ?? ""}</small></td><td><DeleteRecordForm table="class_subjects" id={item.id} /></td></tr>) : <tr><td colSpan={3}><EmptyState label="assignments" /></td></tr>}</tbody></table><Pagination section={section} search={search} page={page} hasNext={assignments.length > pageSize} /></div></>}
      </section></div>
  </main>;
}