import Link from "next/link";

import { AttendanceMarker } from "@/components/attendance/attendance-marker";
import { requireAttendanceContext } from "@/lib/attendance/context";

type SearchParams = Promise<{ date?: string; classId?: string; sectionId?: string }>;
export default async function AttendancePage({ searchParams }: { searchParams: SearchParams }) { const params = await searchParams; const { supabase, schoolId } = await requireAttendanceContext("manage"); const date = params.date ?? new Date().toISOString().slice(0, 10); const [{ data: classes }, { data: sections }] = await Promise.all([supabase.from("classes").select("id,name").eq("school_id", schoolId).eq("status", "active").order("name"), supabase.from("sections").select("id,name,class_id").eq("school_id", schoolId).eq("status", "active").order("name")]); let students: Array<{ id: string; enrollmentId: string; name: string; admissionNumber: string; status?: string; remarks?: string | null }> = []; if (params.classId && params.sectionId) { const { data } = await supabase.from("student_enrollments").select("id,student_id,students(first_name,middle_name,last_name,admission_number),student_attendance(status,remarks)").eq("school_id", schoolId).eq("class_id", params.classId).eq("section_id", params.sectionId).eq("status", "active"); students = (data ?? []).map((row) => { const student = Array.isArray(row.students) ? row.students[0] : row.students; const attendance = Array.isArray(row.student_attendance) ? row.student_attendance[0] : row.student_attendance; return { id: row.student_id, enrollmentId: row.id, name: `${student?.first_name ?? ""} ${student?.middle_name ?? ""} ${student?.last_name ?? ""}`.trim(), admissionNumber: student?.admission_number ?? "", status: attendance?.status, remarks: attendance?.remarks }; }); }
  const present = students.filter((student) => student.status === "present").length;
  const absent = students.filter((student) => student.status === "absent").length;
  const late = students.filter((student) => student.status === "late").length;
  const excused = students.filter((student) => student.status === "excused").length;
  return <main className="attendance-shell"><header className="students-header"><Link className="wordmark" href="/"><span className="wordmark-mark">S</span><span>schooliva</span></Link><div><Link className="text-action" href="/attendance/reports">Reports -&gt;</Link><Link className="text-action students-header-link" href="/dashboard">Dashboard -&gt;</Link></div></header><section className="module-page-header"><div className="module-page-header__row"><div><p className="module-page-header__eyebrow">Daily operations</p><h1>Attendance.</h1><p>Mark daily attendance from the active enrollment roster.</p></div></div></section><section className="module-kpi-grid"><article className="module-kpi"><span>Present</span><strong>{present}</strong></article><article className="module-kpi"><span>Absent</span><strong>{absent}</strong></article><article className="module-kpi"><span>Late</span><strong>{late}</strong></article><article className="module-kpi"><span>Excused</span><strong>{excused}</strong></article></section><form className="attendance-filters"><label>Date<input type="date" name="date" defaultValue={date} /></label><label>Class<select name="classId" defaultValue={params.classId ?? ""}><option value="">Select class</option>{(classes ?? []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Section<select name="sectionId" defaultValue={params.sectionId ?? ""}><option value="">Select section</option>{(sections ?? []).filter((item) => !params.classId || item.class_id === params.classId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="submit">Load roster</button></form>{params.classId && params.sectionId ? <AttendanceMarker attendanceDate={date} classId={params.classId} sectionId={params.sectionId} students={students} /> : <div className="student-empty attendance-empty"><h3>Select a class, section and date</h3><p>Enrolled students will appear here for marking.</p></div>}</main>; }