import Link from "next/link";

import { AttendanceMarker } from "@/components/attendance/attendance-marker";
import { requireAttendanceContext } from "@/lib/attendance/context";

type SearchParams = Promise<{ date?: string; classId?: string; sectionId?: string }>;
export default async function AttendancePage({ searchParams }: { searchParams: SearchParams }) { const params = await searchParams; const { supabase, schoolId } = await requireAttendanceContext("manage"); const date = params.date ?? new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); const [{ data: classes }, { data: sections }] = await Promise.all([supabase.from("classes").select("id,name").eq("school_id", schoolId).eq("status", "active").order("name"), supabase.from("sections").select("id,name,class_id").eq("school_id", schoolId).eq("status", "active").order("name")]); const selectedClass = (classes ?? []).some((item) => item.id === params.classId); const selectedSection = (sections ?? []).find((item) => item.id === params.sectionId && item.class_id === params.classId); const hasRosterSelection = Boolean(selectedClass && selectedSection); let students: Array<{ id: string; enrollmentId: string; name: string; admissionNumber: string; status?: string; remarks?: string | null }> = []; if (hasRosterSelection) { const { data } = await supabase.from("student_enrollments").select("id,student_id,students(first_name,middle_name,last_name,admission_number),student_attendance(status,remarks,attendance_date)").eq("school_id", schoolId).eq("class_id", params.classId!).eq("section_id", params.sectionId!).eq("status", "active").eq("student_attendance.attendance_date", date); students = (data ?? []).map((row) => { const student = Array.isArray(row.students) ? row.students[0] : row.students; const attendance = Array.isArray(row.student_attendance) ? row.student_attendance[0] : row.student_attendance; return { id: row.student_id, enrollmentId: row.id, name: `${student?.first_name ?? ""} ${student?.middle_name ?? ""} ${student?.last_name ?? ""}`.trim(), admissionNumber: student?.admission_number ?? "", status: attendance?.status, remarks: attendance?.remarks }; }); }
  const present = students.filter((student) => !student.status || student.status === "present" || student.status === "half_day").length;
  const absent = students.filter((student) => student.status === "absent").length;
  const late = students.filter((student) => student.status === "late").length;
  const excused = students.filter((student) => student.status === "excused").length;
  const attendanceTotal = students.length;
  const progress = (value: number) => attendanceTotal ? Math.round((value / attendanceTotal) * 100) : 0;
  return <main className="attendance-shell"><header className="students-header"><Link className="wordmark" href="/"><span className="wordmark-mark">S</span><span>schooliva</span></Link><div><Link className="text-action" href="/attendance/reports">Reports -&gt;</Link><Link className="text-action students-header-link" href="/dashboard">Dashboard -&gt;</Link></div></header><section className="module-page-header"><div className="module-page-header__row"><div><p className="module-page-header__eyebrow">Daily operations</p><h1>Attendance.</h1><p>Mark daily attendance from the active enrollment roster.</p></div></div></section>{hasRosterSelection && <section className="attendance-summary-panel" aria-label="Attendance summary"><div><span className="attendance-summary-panel__label">Attendance summary</span><strong>{students.length} enrolled students</strong><small>{date}</small></div><div className="attendance-summary-panel__statuses"><span className="attendance-summary-status attendance-summary-status--present"><i style={{ background: `conic-gradient(#047857 ${progress(present)}%, #e5eaf1 0)` }}><b>{present}</b></i><em>Present</em><small>{progress(present)}%</small></span><span className="attendance-summary-status attendance-summary-status--absent"><i style={{ background: `conic-gradient(#be123c ${progress(absent)}%, #e5eaf1 0)` }}><b>{absent}</b></i><em>Absent</em><small>{progress(absent)}%</small></span><span className="attendance-summary-status attendance-summary-status--late"><i style={{ background: `conic-gradient(#a16207 ${progress(late)}%, #e5eaf1 0)` }}><b>{late}</b></i><em>Late</em><small>{progress(late)}%</small></span><span className="attendance-summary-status attendance-summary-status--excused"><i style={{ background: `conic-gradient(#1d4ed8 ${progress(excused)}%, #e5eaf1 0)` }}><b>{excused}</b></i><em>Excused</em><small>{progress(excused)}%</small></span></div></section>}<form className="attendance-filters"><label>Date<input type="date" name="date" defaultValue={date} /></label><label>Class<select name="classId" defaultValue={params.classId ?? ""}><option value="">Select class</option>{(classes ?? []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Section<select name="sectionId" defaultValue={selectedSection?.id ?? ""}><option value="">Select section</option>{(sections ?? []).filter((item) => !params.classId || item.class_id === params.classId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="submit">Load roster</button></form>{hasRosterSelection ? <AttendanceMarker attendanceDate={date} classId={params.classId!} sectionId={params.sectionId!} students={students} /> : <div className="student-empty attendance-empty"><h3>Select a class, section and date</h3><p>Choose a matching class and section to load the enrolled roster.</p></div>}</main>; }