"use client";
import { useActionState } from "react";
import { saveCurriculum, saveTeacherSubject } from "@/app/actions/curriculum";
import { SubmitButton } from "@/components/auth/submit-button";
import type { CurriculumFormState } from "@/lib/curriculum/schemas";
type Option = { id: string; name: string };
function Feedback({ state }: { state: CurriculumFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Select({ label, name, options }: { label: string; name: string; options: Option[] }) { return <label className="student-field">{label}<select name={name} required><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>; }
export function CurriculumForm({ sessions, classes, subjects }: { sessions: Option[]; classes: Option[]; subjects: Option[] }) { const [state, action] = useActionState(saveCurriculum, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Academic session" name="academicSessionId" options={sessions} /><Select label="Class" name="classId" options={classes} /><Select label="Subject" name="subjectId" options={subjects} /><label className="student-field">Credits<input name="credits" type="number" min="0" step="0.01" /></label><label className="student-field">Grading weight %<input name="gradingWeight" type="number" min="0" max="100" step="0.01" /></label><label className="student-field">Status<select name="status" defaultValue="active"><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label></div><p className="student-form-note">Existing session mappings remain unchanged when a new configuration is added.</p><SubmitButton>Add curriculum mapping</SubmitButton></form>; }
export function TeacherSubjectForm({ sessions, teachers, subjects, classes }: { sessions: Option[]; teachers: Option[]; subjects: Option[]; classes: Option[] }) { const [state, action] = useActionState(saveTeacherSubject, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Academic session" name="academicSessionId" options={sessions} /><Select label="Teacher" name="teacherId" options={teachers} /><Select label="Subject" name="subjectId" options={subjects} /><label className="student-field">Class (optional)<select name="classId"><option value="">All classes</option>{classes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><SubmitButton>Assign teacher to subject</SubmitButton></form>; }