"use client";

import { useActionState } from "react";

import { addTeacherAssignment, deleteTeacherAssignment, saveStaff, saveTeacher } from "@/app/actions/people";
import { SubmitButton } from "@/components/auth/submit-button";
import type { PeopleFormState } from "@/lib/people/schemas";

type RecordValue = Record<string, string | null | undefined>;
function Feedback({ state }: { state: PeopleFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Field({ label, name, type = "text", value, required = false }: { label: string; name: string; type?: string; value?: string | null; required?: boolean }) { return <label className="student-field">{label}<input name={name} type={type} defaultValue={value ?? ""} required={required} /></label>; }
function Status({ value = "active" }: { value?: string | null }) { return <label className="student-field">Employment status<select name="employmentStatus" defaultValue={value ?? "active"}><option value="active">Active</option><option value="inactive">Inactive</option><option value="on_leave">On leave</option><option value="terminated">Terminated</option></select></label>; }

export function TeacherForm({ teacher }: { teacher?: RecordValue }) {
  const [state, action] = useActionState(saveTeacher, undefined);
  return <form action={action} className="student-form"><Feedback state={state} />{teacher?.id && <input type="hidden" name="id" value={teacher.id} />}<div className="student-form-section"><h3>Identity</h3><div className="student-form-grid"><Field label="Employee ID" name="employeeCode" value={teacher?.employee_code} required /><Field label="First name" name="firstName" value={teacher?.first_name} required /><Field label="Last name" name="lastName" value={teacher?.last_name} required /><Field label="Date of birth" name="dateOfBirth" type="date" value={teacher?.date_of_birth} /><label className="student-field">Gender<select name="gender" defaultValue={teacher?.gender ?? ""}><option value="">Select gender</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="undisclosed">Prefer not to say</option></select></label><Status value={teacher?.employment_status} /></div></div><div className="student-form-section"><h3>Contact and professional details</h3><div className="student-form-grid"><Field label="Email" name="email" type="email" value={teacher?.email} /><Field label="Phone" name="phone" value={teacher?.phone} /><Field label="Joining date" name="joiningDate" type="date" value={teacher?.joining_date} /><Field label="Qualification" name="qualification" value={teacher?.qualification} /><Field label="Specialization" name="specialization" value={teacher?.specialization} /><label className="student-field student-field-wide">Address<textarea name="address" defaultValue={teacher?.address ?? ""} rows={3} /></label></div></div><SubmitButton>{teacher?.id ? "Save teacher" : "Create teacher"}</SubmitButton></form>;
}

export function StaffForm({ staff }: { staff?: RecordValue }) {
  const [state, action] = useActionState(saveStaff, undefined);
  return <form action={action} className="student-form"><Feedback state={state} />{staff?.id && <input type="hidden" name="id" value={staff.id} />}<div className="student-form-grid"><Field label="Employee ID" name="employeeCode" value={staff?.employee_code} required /><Field label="First name" name="firstName" value={staff?.first_name} required /><Field label="Last name" name="lastName" value={staff?.last_name} required /><Field label="Department" name="department" value={staff?.department} /><Field label="Designation" name="designation" value={staff?.designation} required /><Field label="Email" name="email" type="email" value={staff?.email} /><Field label="Phone" name="phone" value={staff?.phone} /><Field label="Joining date" name="joiningDate" type="date" value={staff?.joining_date} /><Status value={staff?.employment_status} /></div><SubmitButton>{staff?.id ? "Save staff" : "Create staff"}</SubmitButton></form>;
}

export function AssignmentForm({ teacherId, classes, sections, subjects }: { teacherId: string; classes: Array<{ id: string; name: string }>; sections: Array<{ id: string; name: string }>; subjects: Array<{ id: string; name: string }> }) {
  const [state, action] = useActionState(addTeacherAssignment, undefined);
  return <form action={action} className="student-form"><Feedback state={state} /><input type="hidden" name="teacherId" value={teacherId} /><div className="student-form-grid"><label className="student-field">Assignment type<select name="assignmentType" defaultValue="class"><option value="class">Class</option><option value="section">Section</option><option value="subject">Subject</option></select></label><label className="student-field">Class target<select name="classId" defaultValue=""><option value="">Select class target</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="student-field">Section target<select name="sectionId" defaultValue=""><option value="">Select section target</option>{sections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="student-field">Subject target<select name="subjectId" defaultValue=""><option value="">Select subject target</option>{subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><p className="student-form-note">Assignment type ke matching target ko select karein.</p><SubmitButton>Add assignment</SubmitButton></form>;
}

export function DeleteAssignmentForm({ id, teacherId }: { id: string; teacherId: string }) { const [state, action] = useActionState(deleteTeacherAssignment, undefined); return <form action={action} className="delete-form"><input type="hidden" name="id" value={id} /><input type="hidden" name="teacherId" value={teacherId} /><button type="submit">Remove</button>{state?.error && <span className="student-error">{state.error}</span>}</form>; }