"use client";

import { useActionState } from "react";
import { saveDriver, saveRoute, saveStop, saveStudentAssignment, saveTransportFee, saveVehicle } from "@/app/actions/transport";
import { SubmitButton } from "@/components/auth/submit-button";
import type { TransportFormState } from "@/lib/transport/schemas";

type Option = { id: string; name: string };

function Feedback({ state }: { state: TransportFormState | undefined }) { return <>{state?.error && <p className="student-error">{state.error}</p>}{state?.success && <p className="student-success">{state.success}</p>}</>; }
function Select({ label, name, options }: { label: string; name: string; options: Option[] }) { return <label className="student-field">{label}<select name={name} required><option value="">Select {label.toLowerCase()}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }

export function DriverForm() { const [state, action] = useActionState(saveDriver, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Full name<input name="fullName" required /></label><label className="student-field">License number<input name="licenseNumber" required /></label><label className="student-field">Phone<input name="phone" /></label><label className="student-field">Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="on_leave">On leave</option></select></label></div><SubmitButton>Add driver</SubmitButton></form>; }
export function VehicleForm({ drivers }: { drivers: Option[] }) { const [state, action] = useActionState(saveVehicle, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Registration number<input name="registrationNumber" required /></label><label className="student-field">Vehicle type<input name="vehicleType" required /></label><label className="student-field">Capacity<input name="capacity" type="number" min="1" required /></label><Select label="Driver" name="driverId" options={drivers} /><label className="student-field">Status<select name="status"><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></select></label><label className="student-field student-field-wide">Notes<textarea name="notes" rows={3} /></label></div><SubmitButton>Add vehicle</SubmitButton></form>; }
export function RouteForm({ vehicles }: { vehicles: Option[] }) { const [state, action] = useActionState(saveRoute, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Route name<input name="name" required /></label><label className="student-field">Route code<input name="routeCode" required /></label><Select label="Vehicle" name="vehicleId" options={vehicles} /><label className="student-field">Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="student-field student-field-wide">Description<textarea name="description" rows={3} /></label></div><SubmitButton>Add route</SubmitButton></form>; }
export function StopForm() { const [state, action] = useActionState(saveStop, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><label className="student-field">Stop name<input name="name" required /></label><label className="student-field">Stop type<select name="stopType"><option value="pickup">Pickup</option><option value="dropoff">Drop-off</option><option value="both">Both</option></select></label><label className="student-field">Address<input name="address" /></label><label className="student-field">Latitude<input name="latitude" type="number" step="0.000001" /></label><label className="student-field">Longitude<input name="longitude" type="number" step="0.000001" /></label></div><SubmitButton>Add stop</SubmitButton></form>; }
export function StudentAssignmentForm({ students, routes, stops }: { students: Option[]; routes: Option[]; stops: Option[] }) { const [state, action] = useActionState(saveStudentAssignment, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Student" name="studentId" options={students} /><Select label="Route" name="routeId" options={routes} /><Select label="Pickup stop" name="pickupStopId" options={stops} /><Select label="Drop-off stop" name="dropoffStopId" options={stops} /><label className="student-field student-field-wide">Notes<textarea name="notes" rows={3} /></label></div><SubmitButton>Assign student</SubmitButton></form>; }
export function TransportFeeForm({ students, routes }: { students: Option[]; routes: Option[] }) { const [state, action] = useActionState(saveTransportFee, undefined); return <form action={action} className="student-form"><Feedback state={state} /><div className="student-form-grid"><Select label="Student" name="studentId" options={students} /><Select label="Route" name="routeId" options={routes} /><label className="student-field">Amount<input name="amount" type="number" min="0" step="0.01" required /></label><label className="student-field">Frequency<select name="frequency"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="term">Term</option><option value="yearly">Yearly</option></select></label><label className="student-field">Due day<input name="dueDay" type="number" min="1" max="31" required /></label></div><SubmitButton>Set fee</SubmitButton></form>; }
